name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Login to GHCR
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u serdarsahin1995 --password-stdin
      
    - name: Build Docker image
      run: docker build -t ghcr.io/serdarsahin1995/generic-modul:${{ github.sha }} .
      
    - name: Push Docker image
      run: docker push ghcr.io/serdarsahin1995/generic-modul:${{ github.sha }}
      
    - name: Deploy to Kubernetes
      run: |
        echo "Image pushed: ghcr.io/serdarsahin1995/generic-modul:${{ github.sha }}"
        echo "Update your Kubernetes deployment with this image tag"